### ISSUE TITLE
Coding standards nakijken en feedback geven

### ISSUE THREAD

**Issue by sasjakoning** [sasjakoning/blok-tech-2022-groepoek#10]
https://github.com/sasjakoning/blok-tech-2022-groepoek/wiki/coding

**Comment by 03Sandraa** [comment]
Misschien kunnen we beschrijven welke formatter(s) we gebruiken en met welke instellingen (bijvoorbeeld de standaard instellingen), zodat voor iedereen de formatter hetzelfde doet.

Voor de rest vind ik het duidelijk en overzichtelijk uitgewerkt.

**Comment by ChrisvanHvA** [comment]
Ik ben het eens met 03Sandraa, het toevoegen van een Linter is ook nog zeker van belang, als ik toestemming heb kan ik voor CSS wel een StyleLint document opzetten die onze teamgenoten kunnen implementeren in hun CSS.

**Comment by sasjakoning** [comment]
> Ik ben het eens met 03Sandraa, het toevoegen van een Linter is ook nog zeker van belang, als ik toestemming heb kan ik voor CSS wel een StyleLint document opzetten die onze teamgenoten kunnen implementeren in hun CSS.

Prima
