### ISSUE TITLE
Github standards nakijken en feedback geven

### ISSUE THREAD

**Issue by sasjakoning** [sasjakoning/blok-tech-2022-groepoek#11]
https://github.com/sasjakoning/blok-tech-2022-groepoek/wiki/github

**Comment by 03Sandraa** [comment]
Duidelijk uitgelegd. Als toevoeging zouden we nog uit kunnen lekken hoe je precies een nieuwe branch maakt.

**Comment by ChrisvanHvA** [comment]
Ziet er goed uit, heb geen verdere opmerkingen
