### ISSUE TITLE
Research new design

### ISSUE THREAD

**Issue by sasjakoning** [sasjakoning/blok-tech-2022-groepoek#6]
op dribbble, pinterest etc, moodboard maken op miro?

**Comment by ChrisvanHvA** [comment]
Op figma kan je onze research terugvinden,
We hebben samen op figma ook gewerkt aan het design en een final versie gemaakt.

Je kan hem hier nog terug vinden: https://www.figma.com/file/JexJxLJcqfuyftNnBAU9tb/groepoek-design?node-id=0%3A1
